---
# templates/minio-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.customerId }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
      customer: {{ .Values.customerId }}
  template:
    metadata:
      labels:
        app: minio
        customer: {{ .Values.customerId }}
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ACCESSKEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_SECRETKEY
            - name: MINIO_CONSOLE_ADDRESS
              value: ":9001"
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          emptyDir: {}